ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - "some.com"
  path: /grafana/?(.*)
grafana.ini:
  server:
    domain: 35.242.230.236
    root_url: http://35.242.230.236/grafana
