# kubectl apply -k github.com/stefanprodan/podinfo//kustomize
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: podinfo
spec:
  rules:
  - host: podinfo.kops.dh4r4pvj.ga
    http:
      paths:
      - path: /podinfo/(.*)
        backend:
          serviceName: podinfo
          servicePort: 9898

