server:
  prefixURL: '/prometheus'
  baseURL: 'http://a312d7f78df794241a320baa5c49f32f-359407809.ap-south-1.elb.amazonaws.com/prometheus'
  ingress:
    enabled: true
    hosts:
            #- ac43f578216c447c788bd61e3d6f25a5-df40e78666cd7271.elb.ap-south-1.amazonaws.com/prometheus/?(.*)
    - a312d7f78df794241a320baa5c49f32f-359407809.ap-south-1.elb.amazonaws.com/prometheus
    annotations:
      kubernetes.io/ingress.class: "nginx"
      #      nginx.ingress.kubernetes.io/rewrite-target: /$1

