name: Eleventy Build
on:
  push:
    branches:
      - source  # default branch

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
        with:
          # args: --output _dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master  # deploying branch